# Generated by Django 5.0.1 on 2025-10-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('store', 'Store'), ('headquarters', 'Head Quarters'), ('warehouse', 'Warehouse'), ('distribution', 'Distribution Center'), ('factory', 'Factory'), ('showroom', 'Showroom')], default='store', max_length=20),
        ),
    ]
