# Generated by Django 5.0.1 on 2025-10-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_location_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo image (recommended size: 200x200px)', null=True, upload_to='company_logos/'),
        ),
    ]
