# Generated by Django 5.0.1 on 2025-10-25 02:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Master data name', max_length=100)),
                ('code', models.CharField(help_text='Short code for master data', max_length=20)),
                ('master_type', models.CharField(choices=[('bank', 'Bank'), ('payment_method', 'Payment Method'), ('currency', 'Currency'), ('tax_type', 'Tax Type'), ('discount_type', 'Discount Type'), ('loyalty_type', 'Loyalty Type'), ('customer_type', 'Customer Type'), ('supplier_type', 'Supplier Type'), ('product_category', 'Product Category'), ('unit_of_measure', 'Unit of Measure'), ('warehouse', 'Warehouse'), ('counter', 'Counter'), ('shift', 'Shift'), ('reason_code', 'Reason Code'), ('other', 'Other')], help_text='Type of master data', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of master data', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this master data is active')),
                ('is_system_generated', models.BooleanField(default=False, help_text='System generated vs user created')),
                ('requires_authorization', models.BooleanField(default=False, help_text='Requires manager authorization')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display in POS')),
                ('icon_name', models.CharField(blank=True, help_text='Icon name for UI', max_length=50, null=True)),
                ('color_code', models.CharField(default='#2196F3', help_text='Color code for UI (hex)', max_length=7)),
                ('allow_edit', models.BooleanField(default=True, help_text='Allow editing of this master data')),
                ('allow_delete', models.BooleanField(default=True, help_text='Allow deletion of this master data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_masters_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_masters_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS Master',
                'verbose_name_plural': 'POS Masters',
                'db_table': 'pos_masters',
                'ordering': ['master_type', 'display_order', 'name'],
                'unique_together': {('code', 'master_type')},
            },
        ),
        migrations.CreateModel(
            name='POSMasterHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text='Field that was changed', max_length=50)),
                ('old_value', models.TextField(help_text='Previous value')),
                ('new_value', models.TextField(help_text='New value')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for change', null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pos_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='pos_masters.posmaster')),
            ],
            options={
                'verbose_name': 'POS Master History',
                'verbose_name_plural': 'POS Master History',
                'db_table': 'pos_master_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='POSMasterSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enable_auto_code_generation', models.BooleanField(default=True, help_text='Enable automatic code generation')),
                ('code_prefix_length', models.PositiveIntegerField(default=3, help_text='Length of code prefix')),
                ('allow_duplicate_names', models.BooleanField(default=False, help_text='Allow duplicate names across types')),
                ('default_display_order', models.PositiveIntegerField(default=0, help_text='Default display order for new items')),
                ('show_inactive_items', models.BooleanField(default=False, help_text='Show inactive items in POS')),
                ('require_description', models.BooleanField(default=False, help_text='Require description for all master data')),
                ('validate_code_format', models.BooleanField(default=True, help_text='Validate code format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_master_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS Master Settings',
                'verbose_name_plural': 'POS Master Settings',
                'db_table': 'pos_master_settings',
            },
        ),
        migrations.CreateModel(
            name='POSMasterMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapping_type', models.CharField(choices=[('geographical', 'Geographical Data'), ('business_rule', 'Business Rule'), ('pay_mode', 'Pay Mode'), ('user_role', 'User Role'), ('terminal', 'Terminal'), ('other', 'Other')], max_length=20)),
                ('mapped_entity_id', models.CharField(help_text='ID of the mapped entity', max_length=100)),
                ('mapped_entity_name', models.CharField(help_text='Name of the mapped entity', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_master_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('pos_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='pos_masters.posmaster')),
            ],
            options={
                'verbose_name': 'POS Master Mapping',
                'verbose_name_plural': 'POS Master Mappings',
                'db_table': 'pos_master_mappings',
                'unique_together': {('pos_master', 'mapping_type', 'mapped_entity_id')},
            },
        ),
    ]
