# Generated by Django 5.0.1 on 2025-10-25 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_masters', '0002_create_default_pos_masters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyDenomination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('denomination_type', models.CharField(choices=[('note', 'Note'), ('coin', 'Coin')], help_text='Note or Coin', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Denomination value', max_digits=18)),
                ('display_name', models.CharField(help_text="Display name (e.g., '$100', '₹500')", max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this denomination is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_denominations_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(limit_choices_to={'master_type': 'currency'}, on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='pos_masters.posmaster')),
            ],
            options={
                'verbose_name': 'Currency Denomination',
                'verbose_name_plural': 'Currency Denominations',
                'db_table': 'currency_denominations',
                'ordering': ['currency', '-value'],
                'unique_together': {('currency', 'value', 'denomination_type')},
            },
        ),
    ]
