# Generated by Django 5.0.1 on 2025-10-31 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_attribute_attributevalue'),
        ('organization', '0003_company_logo'),
        ('pos_masters', '0003_add_currency_denomination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Template name (e.g., 'Default Estimation Print Template')", max_length=200)),
                ('template_type', models.CharField(choices=[('estimation', 'Estimation'), ('gift_voucher', 'Gift Voucher'), ('receipt', 'Receipt'), ('payment', 'Payment'), ('refund', 'Refund'), ('sales_order', 'Sales Order'), ('sales_return_request', 'Sales Return Request'), ('inter_company_sales', 'Inter Company Sales'), ('default', 'Default')], default='default', max_length=50)),
                ('template_content', models.TextField(blank=True, help_text='Template structure/content (JSON or formatted text)')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default template for this type?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Printer Template',
                'verbose_name_plural': 'Printer Templates',
                'db_table': 'printer_templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Terminal name', max_length=100)),
                ('terminal_code', models.CharField(help_text='Unique terminal code', max_length=20, unique=True)),
                ('terminal_type', models.CharField(choices=[('till', 'Till'), ('counter', 'Counter'), ('kiosk', 'Kiosk'), ('mobile', 'Mobile')], default='till', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('floor_location', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('system_name', models.CharField(blank=True, help_text='System hostname (auto-generated from hostname, not editable by user)', max_length=100)),
                ('auto_login_pos', models.BooleanField(default=False, help_text='Enable automatic login to POS system')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('operating_hours', models.CharField(blank=True, max_length=200, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, help_text='Format: XX:XX:XX:XX:XX:XX', max_length=17, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('network_type', models.CharField(choices=[('ethernet', 'Ethernet'), ('wifi', 'WiFi'), ('cellular', 'Cellular')], default='ethernet', max_length=20)),
                ('wifi_ssid', models.CharField(blank=True, max_length=100, null=True)),
                ('wifi_password', models.CharField(blank=True, max_length=100, null=True)),
                ('hardware_config', models.JSONField(blank=True, default=dict, help_text='Printer, scanner, display, cash drawer settings')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('time_format', models.CharField(default='24', help_text='12 or 24', max_length=10)),
                ('allow_discounts', models.BooleanField(default=True)),
                ('allow_refunds', models.BooleanField(default=True)),
                ('require_customer_info', models.BooleanField(default=False)),
                ('max_transaction_amount', models.DecimalField(decimal_places=2, default=100000, max_digits=18)),
                ('min_transaction_amount', models.DecimalField(decimal_places=2, default=1, max_digits=18)),
                ('max_discount_percentage', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('require_manager_approval', models.BooleanField(default=False)),
                ('auto_receipt', models.BooleanField(default=True)),
                ('auto_print', models.BooleanField(default=True)),
                ('enable_loyalty', models.BooleanField(default=False)),
                ('enable_offline_mode', models.BooleanField(default=True)),
                ('sync_interval', models.PositiveIntegerField(default=300, help_text='Seconds')),
                ('session_timeout', models.PositiveIntegerField(default=900, help_text='Seconds')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('enable_tax_calculation', models.BooleanField(default=True)),
                ('auto_backup', models.BooleanField(default=True)),
                ('backup_interval', models.PositiveIntegerField(default=3600, help_text='Seconds')),
                ('backup_retention', models.PositiveIntegerField(default=30, help_text='Days')),
                ('require_pin', models.BooleanField(default=False)),
                ('audit_log_enabled', models.BooleanField(default=True)),
                ('enable_biometric', models.BooleanField(default=False)),
                ('max_login_attempts', models.PositiveIntegerField(default=3)),
                ('lockout_duration', models.PositiveIntegerField(default=900, help_text='Seconds')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('error', 'Error')], default='active', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='organization.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminals_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='organization.location')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminals_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminals',
                'db_table': 'pos_terminals',
                'ordering': ['terminal_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TerminalDepartmentMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allow', models.BooleanField(default=False, help_text='Allow access to this department on this terminal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department/Category that can be accessed on this terminal', on_delete=django.db.models.deletion.CASCADE, related_name='terminal_mappings', to='categories.category')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_mappings', to='pos_masters.terminal')),
            ],
            options={
                'verbose_name': 'Terminal Department Mapping',
                'verbose_name_plural': 'Terminal Department Mappings',
                'db_table': 'terminal_department_mappings',
            },
        ),
        migrations.CreateModel(
            name='TerminalTenderMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tender_type', models.CharField(choices=[('cards', 'Cards'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('credit', 'Credit'), ('credit_note', 'CreditNote'), ('due', 'Due'), ('coupons', 'Coupons'), ('fcoupons', 'FCoupons'), ('currency', 'Currency')], max_length=50)),
                ('minimum_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum transaction value allowed for this tender type', max_digits=18)),
                ('maximum_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum transaction value allowed for this tender type (0 = no limit)', max_digits=18)),
                ('allow_tender', models.BooleanField(default=False, help_text='Allow this tender type for payments')),
                ('allow_refund', models.BooleanField(default=False, help_text='Allow this tender type for refunds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_mappings', to='pos_masters.terminal')),
            ],
            options={
                'verbose_name': 'Terminal Tender Mapping',
                'verbose_name_plural': 'Terminal Tender Mappings',
                'db_table': 'terminal_tender_mappings',
            },
        ),
        migrations.CreateModel(
            name='TerminalTransactionSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('estimation', 'Estimation'), ('gift_voucher', 'Gift Voucher'), ('inter_company_sales', 'Inter Company Sales'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('refund', 'Refund'), ('sales_order', 'Sales Order'), ('sales_return_request', 'Sales Return Request')], max_length=50)),
                ('allow', models.BooleanField(default=False, help_text='Allow this transaction type on this terminal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_settings_created', to=settings.AUTH_USER_MODEL)),
                ('printer_template', models.ForeignKey(blank=True, help_text='Printer template to use for this transaction type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_masters.printertemplate')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_settings', to='pos_masters.terminal')),
            ],
            options={
                'verbose_name': 'Terminal Transaction Setting',
                'verbose_name_plural': 'Terminal Transaction Settings',
                'db_table': 'terminal_transaction_settings',
            },
        ),
        migrations.AddIndex(
            model_name='printertemplate',
            index=models.Index(fields=['template_type', 'is_default'], name='printer_tem_templat_9ecdba_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['terminal_code'], name='pos_termina_termina_44969e_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['company', 'location'], name='pos_termina_company_5f7d18_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['status', 'is_active'], name='pos_termina_status_f855f6_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaldepartmentmapping',
            index=models.Index(fields=['terminal', 'department'], name='terminal_de_termina_54c9c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='terminaldepartmentmapping',
            unique_together={('terminal', 'department')},
        ),
        migrations.AddIndex(
            model_name='terminaltendermapping',
            index=models.Index(fields=['terminal', 'tender_type'], name='terminal_te_termina_7711a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='terminaltendermapping',
            unique_together={('terminal', 'tender_type')},
        ),
        migrations.AddIndex(
            model_name='terminaltransactionsetting',
            index=models.Index(fields=['terminal', 'transaction_type'], name='terminal_tr_termina_66bf7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='terminaltransactionsetting',
            unique_together={('terminal', 'transaction_type')},
        ),
    ]
