# Generated by Django 5.2.7 on 2025-11-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_masters', '0006_settlementreason'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='settlementreason',
            new_name='pos_settlem_reason__84bf96_idx',
            old_name='pos_settle_reason_active_idx',
        ),
        migrations.RenameIndex(
            model_name='settlementreason',
            new_name='pos_settlem_module__321bb4_idx',
            old_name='pos_settle_module_ref_idx',
        ),
        migrations.AlterField(
            model_name='posmaster',
            name='master_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('payment_method', 'Payment Method'), ('currency', 'Currency'), ('tax_type', 'Tax Type'), ('discount_type', 'Discount Type'), ('loyalty_type', 'Loyalty Type'), ('customer_type', 'Customer Type'), ('supplier_type', 'Supplier Type'), ('product_category', 'Product Category'), ('unit_of_measure', 'Unit of Measure'), ('warehouse', 'Warehouse'), ('counter', 'Counter'), ('shift', 'Shift'), ('reason_code', 'Reason Code'), ('sale_type', 'Sale Type'), ('other', 'Other')], help_text='Type of master data', max_length=20),
        ),
    ]
