# Generated by Django 5.2.7 on 2025-11-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_itemcategory_remove_category_parent_itemsubcategory_and_more'),
        ('pos_masters', '0007_rename_pos_settle_reason_active_idx_pos_settlem_reason__84bf96_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminaldepartmentmapping',
            name='department',
            field=models.ForeignKey(help_text='Department/Category that can be accessed on this terminal', on_delete=django.db.models.deletion.CASCADE, related_name='terminal_mappings', to='categories.productclassification'),
        ),
    ]
