# Generated by Django 5.0.1 on 2025-11-19 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_remove_itemsubcategory_category_and_more'),
        ('pos_masters', '0008_alter_terminaldepartmentmapping_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminaldepartmentmapping',
            name='department',
            field=models.ForeignKey(help_text='Department/Category that can be accessed on this terminal', on_delete=django.db.models.deletion.CASCADE, related_name='terminal_mappings', to='categories.category'),
        ),
    ]
