#!/usr/bin/env python
"""
Populate all menu items from frontend sidebar structure
Creates all menu items from the current sidebar
"""

import os
import sys
import django

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

django.setup()

from users.models import MenuItemType

def populate_all_menu_items():
    """Populate all menu items from frontend sidebar structure"""
    
    # Menu items from frontend/src/utils/menuStructure.js
    menu_items = [
        # Home
        {
            'display_name': 'Dashboard',
            'menu_item_id': 'dashboard',
            'menu_type': 'DASHBOARD',
            'transaction_subtype': None,
            'category': 'Home',
            'path': '/',
            'description': 'Main dashboard and overview',
            'is_active': True,
            'order': 10,
        },
        
        # User & Permissions
        {
            'display_name': 'Role Permissions',
            'menu_item_id': 'user_permissions',
            'menu_type': 'SECURITY',
            'transaction_subtype': None,
            'category': 'User & Permissions',
            'path': '/user-permissions',
            'description': 'Manage user roles and permissions',
            'is_active': True,
            'order': 10,
        },
        {
            'display_name': 'POS Function Mapping',
            'menu_item_id': 'pos_function_mapping',
            'menu_type': 'SECURITY',
            'transaction_subtype': None,
            'category': 'User & Permissions',
            'path': '/user-permissions/pos-functions',
            'description': 'Map POS functions to user roles',
            'is_active': True,
            'order': 20,
        },
        
        # Master Data Management
        {
            'display_name': 'Merchandise',
            'menu_item_id': 'master_configuration',
            'menu_type': 'MASTER',
            'transaction_subtype': None,
            'category': 'Master Data Management',
            'path': '/master-data/configuration',
            'description': 'Configure merchandise and product master data',
            'is_active': True,
            'order': 10,
        },
        {
            'display_name': 'General',
            'menu_item_id': 'master_general',
            'menu_type': 'MASTER',
            'transaction_subtype': None,
            'category': 'Master Data Management',
            'path': '/master-data/general',
            'description': 'General master data configuration',
            'is_active': True,
            'order': 20,
        },
        {
            'display_name': 'UOM Setup',
            'menu_item_id': 'master_uom_setup',
            'menu_type': 'MASTER',
            'transaction_subtype': None,
            'category': 'Master Data Management',
            'path': '/master-data/uom-setup',
            'description': 'Unit of Measurement setup',
            'is_active': True,
            'order': 30,
        },
        {
            'display_name': 'UOM Conversion',
            'menu_item_id': 'master_uom_conversion',
            'menu_type': 'MASTER',
            'transaction_subtype': None,
            'category': 'Master Data Management',
            'path': '/master-data/uom-conversion',
            'description': 'Unit of Measurement conversions',
            'is_active': True,
            'order': 40,
        },
        {
            'display_name': 'Customers',
            'menu_item_id': 'master_customers',
            'menu_type': 'MASTER',
            'transaction_subtype': None,
            'category': 'Master Data Management',
            'path': '/master-data/customers',
            'description': 'Customer master data management',
            'is_active': True,
            'order': 50,
        },
        {
            'display_name': 'Vendors',
            'menu_item_id': 'master_vendors',
            'menu_type': 'MASTER',
            'transaction_subtype': None,
            'category': 'Master Data Management',
            'path': '/master-data/vendors',
            'description': 'Vendor master data management',
            'is_active': True,
            'order': 60,
        },
        
        # Organization Setup
        {
            'display_name': 'Organization Master',
            'menu_item_id': 'organization',
            'menu_type': 'MASTER',
            'transaction_subtype': None,
            'category': 'Organization Setup',
            'path': '/organization',
            'description': 'Organization configuration and setup',
            'is_active': True,
            'order': 10,
        },
        {
            'display_name': 'Tax Setup',
            'menu_item_id': 'item_tax_setup',
            'menu_type': 'MASTER',
            'transaction_subtype': None,
            'category': 'Organization Setup',
            'path': '/item/tax-setup',
            'description': 'Tax configuration and setup',
            'is_active': True,
            'order': 20,
        },
        
        # Item
        {
            'display_name': 'Item Master',
            'menu_item_id': 'item_master',
            'menu_type': 'MASTER',
            'transaction_subtype': None,
            'category': 'Item',
            'path': '/item/item-master',
            'description': 'Item master data management',
            'is_active': True,
            'order': 10,
        },
        {
            'display_name': 'Attributes',
            'menu_item_id': 'item_attributes',
            'menu_type': 'MASTER',
            'transaction_subtype': None,
            'category': 'Item',
            'path': '/item/attributes',
            'description': 'Item attributes configuration',
            'is_active': True,
            'order': 20,
        },
        {
            'display_name': 'Attribute Values',
            'menu_item_id': 'item_attribute_values',
            'menu_type': 'MASTER',
            'transaction_subtype': None,
            'category': 'Item',
            'path': '/item/attribute-values',
            'description': 'Item attribute values management',
            'is_active': True,
            'order': 30,
        },
        
        # Point of Sale
        {
            'display_name': 'Terminal Configuration',
            'menu_item_id': 'pos_terminal_configuration',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'POS',
            'category': 'Point of Sale',
            'path': '/pos/terminal-configuration',
            'description': 'Configure POS terminals',
            'is_active': True,
            'order': 10,
        },
        {
            'display_name': 'Day Management Console',
            'menu_item_id': 'pos_day_management_console',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'POS',
            'category': 'Point of Sale',
            'path': '/pos/day-management-console',
            'description': 'Day management console for POS operations',
            'is_active': True,
            'order': 20,
        },
        {
            'display_name': 'Day Open',
            'menu_item_id': 'pos_day_open',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'POS',
            'category': 'Point of Sale',
            'path': '/pos/day-open',
            'description': 'Open business day for POS operations',
            'is_active': True,
            'order': 30,
        },
        {
            'display_name': 'Session Open',
            'menu_item_id': 'pos_session_open',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'POS',
            'category': 'Point of Sale',
            'path': '/pos/session-open',
            'description': 'Open POS session with opening balance',
            'is_active': True,
            'order': 40,
        },
        {
            'display_name': 'POS Billing',
            'menu_item_id': 'pos_billing',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'POS',
            'category': 'Point of Sale',
            'path': '/pos/desktop',
            'description': 'POS billing and sales operations',
            'is_active': True,
            'order': 50,
        },
        {
            'display_name': 'Settlement',
            'menu_item_id': 'pos_settlement',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'POS',
            'category': 'Point of Sale',
            'path': '/pos/settlement',
            'description': 'POS settlement and closing operations',
            'is_active': True,
            'order': 60,
        },
        {
            'display_name': 'Session Close',
            'menu_item_id': 'pos_session_close',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'POS',
            'category': 'Point of Sale',
            'path': '/pos/session-close',
            'description': 'Close POS session and reconcile',
            'is_active': True,
            'order': 70,
        },
        {
            'display_name': 'Day End',
            'menu_item_id': 'pos_day_end',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'POS',
            'category': 'Point of Sale',
            'path': '/pos/day-end',
            'description': 'End business day and generate reports',
            'is_active': True,
            'order': 80,
        },
        
        # Inventory Management
        {
            'display_name': 'Inventory',
            'menu_item_id': 'inventory_management',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Inventory Management',
            'path': '/inventory',
            'description': 'Inventory and stock management',
            'is_active': True,
            'order': 10,
        },
        {
            'display_name': 'System Go Live',
            'menu_item_id': 'inventory_go_live',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Inventory Management',
            'path': '/inventory/system-go-live',
            'description': 'System go-live and setup',
            'is_active': True,
            'order': 20,
        },
        
        # Procurement
        {
            'display_name': 'Purchase Request',
            'menu_item_id': 'procurement_purchase_request',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Procurement',
            'path': '/procurement/purchase-request',
            'description': 'Create and manage purchase requests',
            'is_active': True,
            'order': 10,
        },
        {
            'display_name': 'Purchase Enquiry',
            'menu_item_id': 'procurement_purchase_enquiry',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Procurement',
            'path': '/procurement/purchase-enquiry',
            'description': 'Send purchase enquiries to vendors',
            'is_active': True,
            'order': 20,
        },
        {
            'display_name': 'Purchase Quotation',
            'menu_item_id': 'procurement_purchase_quotation',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Procurement',
            'path': '/procurement/purchase-quotation',
            'description': 'Manage purchase quotations',
            'is_active': True,
            'order': 30,
        },
        {
            'display_name': 'Purchase Order',
            'menu_item_id': 'procurement_purchase_order',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Procurement',
            'path': '/procurement/purchase-order',
            'description': 'Create and manage purchase orders',
            'is_active': True,
            'order': 40,
        },
        {
            'display_name': 'Goods Received Note',
            'menu_item_id': 'procurement_goods_received',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Procurement',
            'path': '/procurement/goods-received-note',
            'description': 'Record goods received from vendors',
            'is_active': True,
            'order': 50,
        },
        {
            'display_name': 'Purchase Invoice',
            'menu_item_id': 'procurement_purchase_invoice',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Procurement',
            'path': '/procurement/purchase-invoice',
            'description': 'Process purchase invoices',
            'is_active': True,
            'order': 60,
        },
        {
            'display_name': 'Purchase Return',
            'menu_item_id': 'procurement_purchase_return',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Procurement',
            'path': '/procurement/purchase-return',
            'description': 'Process purchase returns',
            'is_active': True,
            'order': 70,
        },
        {
            'display_name': 'Procurement Advice',
            'menu_item_id': 'procurement_advice',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Procurement',
            'path': '/procurement/procurement-advice',
            'description': 'Procurement advice and recommendations',
            'is_active': True,
            'order': 80,
        },
        
        # Stock Nexus
        {
            'display_name': 'Initial Setup',
            'menu_item_id': 'stock_nexus_initial_setup',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Stock Nexus',
            'path': '/stock-nexus/initial-setup',
            'description': 'Initial stock nexus setup',
            'is_active': True,
            'order': 10,
        },
        {
            'display_name': 'Movement Tracking',
            'menu_item_id': 'stock_nexus_movement_tracking',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Stock Nexus',
            'path': '/stock-nexus/movement-tracking',
            'description': 'Track stock movements and transfers',
            'is_active': True,
            'order': 20,
        },
        {
            'display_name': 'Transfer Confirm',
            'menu_item_id': 'stock_nexus_transfer_confirm',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Stock Nexus',
            'path': '/stock-nexus/transfer-confirm',
            'description': 'Confirm stock transfers',
            'is_active': True,
            'order': 30,
        },
        {
            'display_name': 'Count Adjust',
            'menu_item_id': 'stock_nexus_count_adjust',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Stock Nexus',
            'path': '/stock-nexus/count-adjust',
            'description': 'Stock count adjustments',
            'is_active': True,
            'order': 40,
        },
        
        # Sales
        {
            'display_name': 'Sales',
            'menu_item_id': 'sales_management',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Sales',
            'path': '/sales',
            'description': 'Sales management and operations',
            'is_active': True,
            'order': 10,
        },
        {
            'display_name': 'Sales Order',
            'menu_item_id': 'sales_order_management',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Sales',
            'path': '/sales-order-management',
            'description': 'Sales order management',
            'is_active': True,
            'order': 20,
        },
        {
            'display_name': 'Customer Management',
            'menu_item_id': 'customer_management',
            'menu_type': 'TRANSACTION',
            'transaction_subtype': 'BACKOFFICE',
            'category': 'Sales',
            'path': '/customer-management',
            'description': 'Customer relationship management',
            'is_active': True,
            'order': 30,
        },
        
        # Reports
        {
            'display_name': 'Sales Reports',
            'menu_item_id': 'sales_reports',
            'menu_type': 'SYSTEM',
            'transaction_subtype': None,
            'category': 'Reports',
            'path': '/reports/sales',
            'description': 'Sales and business reports',
            'is_active': True,
            'order': 10,
        },
        {
            'display_name': 'Inventory Reports',
            'menu_item_id': 'inventory_reports',
            'menu_type': 'SYSTEM',
            'transaction_subtype': None,
            'category': 'Reports',
            'path': '/reports/inventory',
            'description': 'Inventory and stock reports',
            'is_active': True,
            'order': 20,
        },
        {
            'display_name': 'POS Reports',
            'menu_item_id': 'pos_reports',
            'menu_type': 'SYSTEM',
            'transaction_subtype': None,
            'category': 'Reports',
            'path': '/reports/pos',
            'description': 'POS operations reports',
            'is_active': True,
            'order': 30,
        },
        
        # System
        {
            'display_name': 'Admin Tools',
            'menu_item_id': 'admin_tools',
            'menu_type': 'SYSTEM',
            'transaction_subtype': None,
            'category': 'System',
            'path': '/settings/admin-tools',
            'description': 'System administration tools',
            'is_active': True,
            'order': 10,
        },
        {
            'display_name': 'Database Configuration',
            'menu_item_id': 'system_settings',
            'menu_type': 'SYSTEM',
            'transaction_subtype': None,
            'category': 'System',
            'path': '/settings',
            'description': 'System configuration and settings',
            'is_active': True,
            'order': 20,
        },
        {
            'display_name': 'Layout Preferences',
            'menu_item_id': 'layout_preferences',
            'menu_type': 'SYSTEM',
            'transaction_subtype': None,
            'category': 'System',
            'path': '/settings/layout-preferences',
            'description': 'UI layout preferences',
            'is_active': True,
            'order': 30,
        },
        {
            'display_name': 'Digital Marketing Console',
            'menu_item_id': 'digital_marketing_console',
            'menu_type': 'SYSTEM',
            'transaction_subtype': None,
            'category': 'System',
            'path': '/settings/digital-marketing',
            'description': 'Digital marketing management',
            'is_active': True,
            'order': 40,
        },
        {
            'display_name': 'Web Console',
            'menu_item_id': 'web_console',
            'menu_type': 'SYSTEM',
            'transaction_subtype': None,
            'category': 'System',
            'path': '/settings/web-console',
            'description': 'Web console for system operations',
            'is_active': True,
            'order': 50,
        },
        {
            'display_name': 'HTML Preview Tool',
            'menu_item_id': 'html_preview_tool',
            'menu_type': 'SYSTEM',
            'transaction_subtype': None,
            'category': 'System',
            'path': '/settings/html-preview',
            'description': 'HTML preview and testing tool',
            'is_active': True,
            'order': 60,
        },
        {
            'display_name': 'DataOps Studio',
            'menu_item_id': 'database_client',
            'menu_type': 'SYSTEM',
            'transaction_subtype': None,
            'category': 'System',
            'path': '/settings/dataops-studio',
            'description': 'Database operations studio',
            'is_active': True,
            'order': 70,
        },
        {
            'display_name': 'Wireframe Launchpad',
            'menu_item_id': 'wireframe_index',
            'menu_type': 'SYSTEM',
            'transaction_subtype': None,
            'category': 'System',
            'path': '/wireframes',
            'description': 'Wireframe launchpad for prototyping',
            'is_active': True,
            'order': 80,
        },
        {
            'display_name': 'Business Rules',
            'menu_item_id': 'business_rules',
            'menu_type': 'SYSTEM',
            'transaction_subtype': None,
            'category': 'System',
            'path': '/business-rules',
            'description': 'Business rules configuration',
            'is_active': True,
            'order': 90,
        },
        {
            'display_name': 'POS Preferences',
            'menu_item_id': 'business_rules_general',
            'menu_type': 'SYSTEM',
            'transaction_subtype': None,
            'category': 'System',
            'path': '/business-rules/general',
            'description': 'POS preferences configuration',
            'is_active': True,
            'order': 100,
        },
    ]

    # Clear existing menu items and create new ones
    MenuItemType.objects.all().delete()
    
    for item_data in menu_items:
        MenuItemType.objects.create(**item_data)

    print(f'Created {MenuItemType.objects.count()} menu items')
    print(f'Active items: {MenuItemType.objects.filter(is_active=True).count()}')
    
    # Display created items by category
    categories = MenuItemType.objects.values_list('category', flat=True).distinct()
    for category in sorted(categories):
        items = MenuItemType.objects.filter(category=category).order_by('order')
        print(f'\n{category} ({items.count()} items):')
        for item in items:
            status = '[ACTIVE]' if item.is_active else '[INACTIVE]'
            print(f'  {status} {item.display_name} ({item.menu_item_id})')

if __name__ == '__main__':
    populate_all_menu_items()
