# Generated by Django 5.0.1 on 2025-10-01 17:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product name (e.g., iPhone 15, Nike Air Max)', max_length=200, unique=True, validators=[django.core.validators.MinValueValidator(2)])),
                ('description', models.TextField(blank=True, help_text='Detailed product description', null=True)),
                ('sku', models.CharField(help_text='Stock Keeping Unit - unique product identifier', max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, help_text='Product barcode (optional)', max_length=100, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price of the product', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price of the product', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity')),
                ('minimum_stock', models.PositiveIntegerField(default=0, help_text='Minimum stock level for alerts')),
                ('maximum_stock', models.PositiveIntegerField(blank=True, help_text='Maximum stock level', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Product weight in kg', max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='Product dimensions (L x W x H)', max_length=100, null=True)),
                ('color', models.CharField(blank=True, help_text='Product color', max_length=50, null=True)),
                ('size', models.CharField(blank=True, help_text='Product size', max_length=50, null=True)),
                ('brand', models.CharField(blank=True, help_text='Product brand', max_length=100, null=True)),
                ('model', models.CharField(blank=True, help_text='Product model', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is active and can be sold')),
                ('is_taxable', models.BooleanField(default=True, help_text='Whether this product is subject to tax')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(blank=True, help_text='Product image', null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku'], name='products_sku_fe2039_idx'), models.Index(fields=['barcode'], name='products_barcode_d008ac_idx'), models.Index(fields=['category'], name='products_categor_4083ff_idx'), models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx')],
            },
        ),
    ]
