# Generated by Django 5.0.1 on 2025-10-02 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Product name (e.g., iPhone 15, Nike Air Max)', max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
