# Generated by Django 5.0.1 on 2025-10-24 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_uom_remove_product_products_sku_fe2039_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UOMConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversion_factor', models.DecimalField(decimal_places=4, help_text='Multiplier to convert from UOM to To UOM', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_uom_conversions', to=settings.AUTH_USER_MODEL)),
                ('from_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='products.uom')),
                ('to_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='products.uom')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_uom_conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UOM Conversion',
                'verbose_name_plural': 'UOM Conversions',
                'db_table': 'products_uom_conversion',
                'ordering': ['from_uom', 'to_uom'],
                'unique_together': {('from_uom', 'to_uom')},
            },
        ),
    ]
