# Generated by Django 5.0.1 on 2025-10-24 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0004_uomconversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ean_upc_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('landing_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('store_pickup', models.BooleanField(default=False)),
                ('sales_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('allow_buy_back', models.BooleanField(default=False)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('tax_code', models.CharField(blank=True, max_length=50, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_slab', models.CharField(blank=True, max_length=50, null=True)),
                ('material_type', models.CharField(choices=[('raw', 'Raw Material'), ('finished', 'Finished Good'), ('semi', 'Semi-Finished'), ('consumable', 'Consumable'), ('service', 'Service')], default='finished', max_length=20)),
                ('material_group', models.CharField(blank=True, max_length=100, null=True)),
                ('item_type', models.CharField(choices=[('spare', 'Spare'), ('device', 'Device'), ('ew', 'EW'), ('accessory', 'Accessory')], default='device', max_length=20)),
                ('exchange_type', models.CharField(choices=[('none', 'None'), ('allowed', 'Allowed'), ('exchange_only', 'Exchange Only')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_items', to='products.uom')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('purchase_uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='products.uom')),
                ('sales_uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='products.uom')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Master',
                'verbose_name_plural': 'Item Masters',
                'db_table': 'products_item_master',
                'ordering': ['item_name'],
            },
        ),
    ]
