# Generated by Django 5.2.7 on 2025-11-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_itemcategory_remove_category_parent_itemsubcategory_and_more'),
        ('products', '0007_brand_department_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='item_category',
            field=models.ForeignKey(blank=True, help_text='Item category for classification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='categories.itemcategory'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='item_subcategory',
            field=models.ForeignKey(blank=True, help_text='Item sub-category for detailed classification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='categories.itemsubcategory'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.productclassification'),
        ),
    ]
