# Generated by Django 5.0.1 on 2025-11-19 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_remove_itemsubcategory_category_and_more'),
        ('products', '0008_itemmaster_item_category_itemmaster_item_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmaster',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='item_subcategory',
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
