# Generated by Django 5.2.9 on 2025-12-12 16:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_itemmaster_item_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_type', models.CharField(choices=[('STOCKED', 'Stocked Product'), ('SERVICE', 'Service'), ('KIT', 'Kit / Package'), ('GIFT', 'Gift Card')], default='STOCKED', max_length=20)),
                ('is_serialized', models.BooleanField(default=False)),
                ('is_lot_tracked', models.BooleanField(default=False)),
                ('is_taxable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('DISCONTINUED', 'Discontinued'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item (Parent)',
                'verbose_name_plural': 'Items (Parent)',
                'db_table': 'products_item',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku_code', models.CharField(max_length=80)),
                ('variant_name', models.CharField(help_text='e.g. Red / M', max_length=200)),
                ('is_default_variant', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item Variant',
                'verbose_name_plural': 'Item Variants',
                'db_table': 'products_item_variant',
                'ordering': ['variant_name'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Variant Attribute',
                'verbose_name_plural': 'Variant Attributes',
                'db_table': 'products_variant_attribute',
            },
        ),
        migrations.RemoveField(
            model_name='advanceditemmaster',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='advanceditemmaster',
            name='purchase_uom',
        ),
        migrations.RemoveField(
            model_name='advanceditemmaster',
            name='sales_uom',
        ),
        migrations.RemoveField(
            model_name='advanceditemmaster',
            name='stock_uom',
        ),
        migrations.RemoveField(
            model_name='advanceditemmaster',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='packagecomponent',
            name='component_item',
        ),
        migrations.RemoveField(
            model_name='itemattribute',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemspecification',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemcomponent',
            name='component_item',
        ),
        migrations.RemoveField(
            model_name='alternateitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itempricehistory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='secondarysupplier',
            name='item',
        ),
        migrations.RemoveField(
            model_name='alternateitem',
            name='alternate_item',
        ),
        migrations.RemoveField(
            model_name='itempackage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemcomponent',
            name='item',
        ),
        migrations.AlterUniqueTogether(
            name='alternateitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='division',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='division',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='itemattribute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='base_uom',
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='purchase_uom',
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='sales_uom',
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='itempackage',
            name='package_uom',
        ),
        migrations.RemoveField(
            model_name='packagecomponent',
            name='package',
        ),
        migrations.RemoveField(
            model_name='itempricehistory',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='itemspecification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itemspecification',
            name='updated_by',
        ),
    ]
