# Generated by Django 5.2.9 on 2025-12-12 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_attributevalue_options_and_more'),
        ('inventory', '0003_alter_inventory_product_and_more'),
        ('organization', '0003_company_logo'),
        ('procurement', '0003_alter_goodsreceivednoteitem_product_and_more'),
        ('products', '0010_item_itemvariant_variantattribute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='supplierbarcode',
            name='secondary_supplier',
        ),
        migrations.AlterModelOptions(
            name='itemtaxdetail',
            options={'verbose_name': 'Item Tax Detail'},
        ),
        migrations.AlterUniqueTogether(
            name='uomconversion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='itemtaxdetail',
            name='applicable_to',
        ),
        migrations.RemoveField(
            model_name='itemtaxdetail',
            name='city',
        ),
        migrations.RemoveField(
            model_name='itemtaxdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='itemtaxdetail',
            name='tax_slab',
        ),
        migrations.RemoveField(
            model_name='itemtaxdetail',
            name='tax_type',
        ),
        migrations.RemoveField(
            model_name='itemtaxdetail',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='organization.company'),
        ),
        migrations.AddField(
            model_name='uom',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uoms', to='organization.company'),
        ),
        migrations.AddField(
            model_name='uomconversion',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_conversions', to='organization.company'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uom',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='uom',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='uomconversion',
            unique_together={('company', 'from_uom', 'to_uom')},
        ),
        migrations.AddField(
            model_name='item',
            name='attribute_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='categories.productattributetemplate'),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='products.brand'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='categories.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organization.company'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='products.uom'),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemtaxdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_details', to='products.item'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_variants', to='organization.company'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.item'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='purchase_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_purchases', to='products.uom'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='sales_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_sales', to='products.uom'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='stock_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_stocks', to='products.uom'),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.attribute'),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.attributevalue'),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='item_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.itemvariant'),
        ),
        migrations.DeleteModel(
            name='ItemAttribute',
        ),
        migrations.DeleteModel(
            name='AlternateItem',
        ),
        migrations.DeleteModel(
            name='ItemComponent',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
    ]
