# Generated by Django 5.2.9 on 2025-12-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_goodsreceivednoteitem_product_and_more'),
        ('products', '0011_delete_product_and_more'),
        ('sales', '0009_alter_dayclose_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemMaster',
        ),
        migrations.DeleteModel(
            name='ItemPackage',
        ),
        migrations.DeleteModel(
            name='PackageComponent',
        ),
        migrations.DeleteModel(
            name='ItemPriceHistory',
        ),
        migrations.DeleteModel(
            name='ItemSpecification',
        ),
        migrations.DeleteModel(
            name='SecondarySupplier',
        ),
        migrations.DeleteModel(
            name='SupplierBarcode',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('company', 'item_code')},
        ),
        migrations.DeleteModel(
            name='AdvancedItemMaster',
        ),
        migrations.AlterUniqueTogether(
            name='itemvariant',
            unique_together={('company', 'sku_code')},
        ),
        migrations.AlterUniqueTogether(
            name='variantattribute',
            unique_together={('item_variant', 'attribute')},
        ),
    ]
