# Generated by Django 5.0.1 on 2025-10-24 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Attribute name (e.g., Color, Size, Brand)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the attribute', null=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('select', 'Select (LOV)')], default='select', help_text='Data type for the attribute', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this attribute is active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying attributes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
                'db_table': 'categories_attribute',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(help_text='The attribute value', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the value', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this value is active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(help_text='The attribute this value belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='categories.attribute')),
            ],
            options={
                'verbose_name': 'Attribute Value',
                'verbose_name_plural': 'Attribute Values',
                'db_table': 'categories_attribute_value',
                'ordering': ['sort_order', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
    ]
