# Generated by Django 5.2.7 on 2025-11-11 10:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_attribute_attributevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item category name (e.g., Electronics, Apparels, Home & Kitchen)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('code', models.CharField(help_text='Item category code (e.g., ELEC, APP, HOME)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the item category', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item category is active and can be used')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying item categories (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'db_table': 'item_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.CreateModel(
            name='ItemSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Item sub-category name (e.g., Mobiles, Televisions, Men's Clothing)", max_length=100)),
                ('code', models.CharField(help_text='Item sub-category code (e.g., MOB, TV, MENS)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of the item sub-category', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item sub-category is active and can be used')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying item sub-categories (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Parent item category', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.itemcategory')),
            ],
            options={
                'verbose_name': 'Item Sub-Category',
                'verbose_name_plural': 'Item Sub-Categories',
                'db_table': 'item_subcategories',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Classification name (e.g., Electronics, Clothing, Food)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True, help_text='Optional description of the classification', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this classification is active and can be used')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying classifications (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent classification for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.productclassification')),
            ],
            options={
                'verbose_name': 'Product Classification',
                'verbose_name_plural': 'Product Classifications',
                'db_table': 'product_classifications',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
