# Generated by Django 5.2.7 on 2025-11-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_itemcategory_remove_category_parent_itemsubcategory_and_more'),
        ('pos_masters', '0008_alter_terminaldepartmentmapping_department'),
        ('products', '0008_itemmaster_item_category_itemmaster_item_subcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterUniqueTogether(
            name='itemsubcategory',
            unique_together={('category', 'code')},
        ),
    ]
