# Generated by Django 5.0.1 on 2025-11-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_remove_itemsubcategory_category_and_more'),
        ('pos_masters', '0009_alter_terminaldepartmentmapping_department'),
        ('products', '0009_remove_itemmaster_item_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCategory',
        ),
        migrations.DeleteModel(
            name='ItemSubCategory',
        ),
        migrations.DeleteModel(
            name='ProductClassification',
        ),
    ]
