# Generated by Django 5.2.9 on 2025-12-12 16:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_delete_itemcategory_delete_itemsubcategory_and_more'),
        ('organization', '0003_company_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ['sort_order', 'value_label'], 'verbose_name': 'Attribute Value', 'verbose_name_plural': 'Attribute Values'},
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('company', 'attribute_code')},
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('company', 'attribute', 'value_code')},
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='organization.company'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='input_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('LIST', 'List'), ('MULTI', 'Multi-Select')], default='LIST', help_text='Data type for the attribute', max_length=20),
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_search_facet',
            field=models.BooleanField(default=False, help_text='Use in search filters'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_variant_dimension',
            field=models.BooleanField(default=False, help_text='Can be used for SKU variants'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='value_source',
            field=models.CharField(choices=[('FIXED_LIST', 'Fixed List'), ('FREE_TEXT', 'Free Text'), ('DERIVED', 'Derived')], default='FIXED_LIST', help_text='Source of attribute values', max_length=20),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='organization.company'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_label',
            field=models.CharField(blank=True, help_text='The attribute value label', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organization.company'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(help_text='Attribute name (e.g., Color, Size, Brand)', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name (e.g., Electronics, Clothing, Food)', max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('company', 'name')},
        ),
        migrations.CreateModel(
            name='ProductAttributeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_code', models.CharField(blank=True, max_length=50, null=True)),
                ('template_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_mode', models.CharField(choices=[('SIMPLE', 'Simple'), ('VARIANT_MATRIX', 'Variant Matrix'), ('HYBRID', 'Hybrid')], default='VARIANT_MATRIX', max_length=20)),
                ('is_core_template', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('item_type_scope', models.CharField(blank=True, choices=[('APPAREL', 'Apparel'), ('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('GROCERY', 'Grocery'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version_no', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_templates', to='organization.company')),
            ],
            options={
                'db_table': 'categories_product_attribute_template',
                'ordering': ['template_name'],
                'unique_together': {('company', 'template_code')},
            },
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='value',
        ),
        migrations.CreateModel(
            name='ProductAttributeTemplateLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_required', models.BooleanField(default=False)),
                ('is_variant_dimension', models.BooleanField(default=False)),
                ('value_mode', models.CharField(choices=[('SINGLE', 'Single Value'), ('MULTI', 'Multi Value'), ('DERIVED', 'Derived')], default='SINGLE', max_length=20)),
                ('sequence_no', models.IntegerField(default=0)),
                ('is_search_facet', models.BooleanField(default=False)),
                ('is_pricing_relevant', models.BooleanField(default=False)),
                ('is_reporting_relevant', models.BooleanField(default=False)),
                ('is_pos_visible', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.attribute')),
                ('default_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.attributevalue')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='categories.productattributetemplate')),
            ],
            options={
                'db_table': 'categories_product_attribute_template_line',
                'ordering': ['sequence_no'],
                'unique_together': {('template', 'attribute')},
            },
        ),
    ]
