# Generated by Django 5.0.1 on 2025-10-02 15:21

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(help_text='Unique customer code (auto-generated)', max_length=20, unique=True)),
                ('first_name', models.CharField(help_text="Customer's first name", max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(help_text="Customer's last name", max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('company_name', models.CharField(blank=True, help_text='Company name (for business customers)', max_length=200, null=True)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('wholesale', 'Wholesale'), ('vip', 'VIP')], default='individual', help_text='Type of customer', max_length=20)),
                ('email', models.EmailField(blank=True, help_text="Customer's email address", max_length=254, null=True)),
                ('phone', models.CharField(help_text="Customer's phone number", max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('mobile', models.CharField(blank=True, help_text="Customer's mobile number", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address_line_1', models.CharField(blank=True, help_text='Street address line 1', max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, help_text='Street address line 2 (optional)', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State/Province', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20, null=True)),
                ('country', models.CharField(default='United States', help_text='Country', max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID/SSN (for business customers)', max_length=50, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Credit limit for the customer', max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Default discount percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this customer is active')),
                ('is_vip', models.BooleanField(default=False, help_text='VIP customer status')),
                ('allow_credit', models.BooleanField(default=False, help_text='Allow credit purchases')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the customer', null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="Customer's date of birth", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_purchase_date', models.DateTimeField(blank=True, help_text='Date of last purchase', null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['customer_code'], name='customers_custome_fdedee_idx'), models.Index(fields=['email'], name='customers_email_92e882_idx'), models.Index(fields=['phone'], name='customers_phone_91048b_idx'), models.Index(fields=['last_name', 'first_name'], name='customers_last_na_89bb5f_idx'), models.Index(fields=['customer_type'], name='customers_custome_3f7c53_idx'), models.Index(fields=['is_active'], name='customers_is_acti_0e47e3_idx')],
            },
        ),
    ]
