# Generated by Django 5.2.7 on 2025-11-15 09:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text='Model name', max_length=100)),
                ('cache_key', models.CharField(help_text='Cache key', max_length=200)),
                ('cache_data', models.JSONField(help_text='Cached data')),
                ('expires_at', models.DateTimeField(help_text='When cache expires')),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='Number of times cache was hit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Data Cache',
                'verbose_name_plural': 'Master Data Cache',
                'db_table': 'masters_cache',
                'ordering': ['model_name', 'cache_key'],
                'indexes': [models.Index(fields=['model_name', 'cache_key'], name='masters_cac_model_n_4940b0_idx'), models.Index(fields=['expires_at'], name='masters_cac_expires_adfd4a_idx')],
                'unique_together': {('model_name', 'cache_key')},
            },
        ),
        migrations.CreateModel(
            name='MasterDataTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Template description', null=True)),
                ('version', models.CharField(default='1.0', help_text='Template version', max_length=20)),
                ('sheet_configurations', models.JSONField(default=dict, help_text='Configuration for each sheet in the template')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Master Data Template',
                'verbose_name_plural': 'Master Data Templates',
                'db_table': 'masters_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(help_text='Name of the upload session', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the upload session', null=True)),
                ('excel_file', models.FileField(help_text='Excel file containing master data', upload_to='master_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Upload progress percentage')),
                ('current_step', models.CharField(blank=True, help_text='Current processing step', max_length=100, null=True)),
                ('total_records', models.PositiveIntegerField(default=0, help_text='Total records to process')),
                ('processed_records', models.PositiveIntegerField(default=0, help_text='Records processed so far')),
                ('successful_records', models.PositiveIntegerField(default=0, help_text='Successfully processed records')),
                ('failed_records', models.PositiveIntegerField(default=0, help_text='Failed records')),
                ('skipped_records', models.PositiveIntegerField(default=0, help_text='Skipped records')),
                ('error_message', models.TextField(blank=True, help_text='Error message if upload failed', null=True)),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Detailed error information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Session',
                'verbose_name_plural': 'Upload Sessions',
                'db_table': 'masters_upload_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sheet_name', models.CharField(help_text='Sheet name where record was found', max_length=100)),
                ('row_number', models.PositiveIntegerField(help_text='Row number in the sheet')),
                ('model_name', models.CharField(help_text='Target model name', max_length=100)),
                ('record_identifier', models.CharField(help_text='Record identifier (e.g., code, name)', max_length=200)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('warning', 'Warning')], help_text='Import result', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Result message', null=True)),
                ('original_data', models.JSONField(default=dict, help_text='Original data from Excel')),
                ('processed_data', models.JSONField(blank=True, default=dict, help_text='Processed data after validation')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='masters.uploadsession')),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'db_table': 'masters_import_log',
                'ordering': ['upload_session', 'sheet_name', 'row_number'],
                'indexes': [models.Index(fields=['upload_session', 'result'], name='masters_imp_upload__7cd281_idx'), models.Index(fields=['sheet_name', 'row_number'], name='masters_imp_sheet_n_1cc425_idx'), models.Index(fields=['model_name'], name='masters_imp_model_n_7ce4ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Rule name', max_length=200)),
                ('model_name', models.CharField(help_text='Target model name', max_length=100)),
                ('field_name', models.CharField(help_text='Target field name', max_length=100)),
                ('rule_type', models.CharField(choices=[('required', 'Required'), ('unique', 'Unique'), ('min_length', 'Minimum Length'), ('max_length', 'Maximum Length'), ('min_value', 'Minimum Value'), ('max_value', 'Maximum Value'), ('regex', 'Regular Expression'), ('email', 'Email'), ('phone', 'Phone'), ('numeric', 'Numeric'), ('positive', 'Positive Number'), ('choice', 'Choice'), ('foreign_key', 'Foreign Key'), ('custom', 'Custom')], help_text='Type of validation rule', max_length=20)),
                ('parameters', models.JSONField(default=dict, help_text='Rule parameters (e.g., min_length, pattern, choices)')),
                ('error_message', models.CharField(help_text='Error message to display', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_validation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validation Rule',
                'verbose_name_plural': 'Validation Rules',
                'db_table': 'masters_validation_rule',
                'ordering': ['model_name', 'field_name', 'name'],
                'unique_together': {('model_name', 'field_name', 'name')},
            },
        ),
    ]
