# Generated by Django 5.2.7 on 2025-11-15 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='error_file',
            field=models.FileField(blank=True, help_text='Excel file with error details', null=True, upload_to='master_upload_errors/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])]),
        ),
    ]
