# Generated by Django 5.0.1 on 2025-10-25 01:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(help_text='Description of what this rule does')),
                ('category', models.CharField(choices=[('stock_management', 'Stock Management'), ('pricing_quantity', 'Pricing & Quantity'), ('discounts_loyalty', 'Discounts & Loyalty'), ('rounding_amounts', 'Rounding & Amounts'), ('customer_sales', 'Customer & Sales Management'), ('billing_documents', 'Billing & Documents'), ('advanced_settings', 'Advanced Settings')], max_length=50)),
                ('rule_type', models.CharField(choices=[('boolean', 'Boolean (Yes/No)'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('string', 'Text'), ('choice', 'Choice')], max_length=20)),
                ('default_value', models.TextField(help_text='Default value as string')),
                ('current_value', models.TextField(help_text='Current value as string')),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('help_text', models.TextField(blank=True, help_text='Help text for users', null=True)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validation rules as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_rules_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_rules_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Rule',
                'verbose_name_plural': 'Business Rules',
                'db_table': 'business_rules',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessRuleHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('business_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='business_rules.businessrule')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Rule History',
                'verbose_name_plural': 'Business Rule History',
                'db_table': 'business_rule_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
