# Generated by Django 5.0.1 on 2025-10-25 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_rules', '0002_create_default_business_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_suspended_bills', models.BooleanField(default=True, help_text='Check for suspended bills before allowing settlement')),
                ('check_partial_transactions', models.BooleanField(default=True, help_text='Check for partial transactions before allowing settlement')),
                ('require_settlement_before_session_close', models.BooleanField(default=True, help_text='Require settlement completion before closing session')),
                ('allow_deferred_settlement', models.BooleanField(default=True, help_text='Allow settlement to be done later (next day)')),
                ('require_session_ownership_to_close', models.BooleanField(default=True, help_text='Only session starter can close the session')),
                ('block_billing_on_pending_settlement', models.BooleanField(default=True, help_text='Block billing if previous session has pending settlement')),
                ('block_session_start_on_pending_settlement', models.BooleanField(default=True, help_text='Block new session start if previous session has pending settlement')),
                ('show_pending_settlement_alert', models.BooleanField(default=True, help_text='Show alert for pending settlements on POS open')),
                ('auto_remind_pending_settlement', models.BooleanField(default=True, help_text='Automatically remind about pending settlements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settlement Settings',
                'verbose_name_plural': 'Settlement Settings',
                'db_table': 'settlement_settings',
            },
        ),
    ]
