# Generated by Django 5.0.1 on 2025-11-07 15:59

from django.db import migrations, models


def populate_business_rule_sequence(apps, schema_editor):
    BusinessRule = apps.get_model('business_rules', 'BusinessRule')
    categories_order = [
        'stock_management',
        'pricing_quantity',
        'discounts_loyalty',
        'rounding_amounts',
        'customer_sales',
        'billing_documents',
        'advanced_settings',
    ]

    sequence = 1
    for category in categories_order:
        rules = BusinessRule.objects.filter(category=category).order_by('name', 'created_at')
        for rule in rules:
            rule.sequence = sequence
            rule.save(update_fields=['sequence'])
            sequence += 1

    remaining_rules = BusinessRule.objects.exclude(category__in=categories_order).order_by('name', 'created_at')
    for rule in remaining_rules:
        rule.sequence = sequence
        rule.save(update_fields=['sequence'])
        sequence += 1


def reverse_sequence(apps, schema_editor):
    BusinessRule = apps.get_model('business_rules', 'BusinessRule')
    BusinessRule.objects.all().update(sequence=0)


class Migration(migrations.Migration):

    dependencies = [
        ('business_rules', '0003_add_settlement_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessrule',
            options={'ordering': ['sequence', 'name'], 'verbose_name': 'Business Rule', 'verbose_name_plural': 'Business Rules'},
        ),
        migrations.AddField(
            model_name='businessrule',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Display order for POS preferences'),
        ),
        migrations.RunPython(populate_business_rule_sequence, reverse_sequence),
    ]
