# Generated by Django 5.0.1 on 2025-11-07 16:07

import uuid
from django.db import migrations, models


def seed_settlement_definitions(apps, schema_editor):
    Definition = apps.get_model('business_rules', 'SettlementSettingDefinition')

    categories = [
        (
            1,
            'settlement_validation',
            'Settlement Validation',
            [
                ('check_suspended_bills', 'Check for Suspended Bills', 'Check for suspended bills before allowing settlement'),
                ('check_partial_transactions', 'Check for Partial Transactions', 'Check for partial transactions before allowing settlement'),
                ('require_settlement_before_session_close', 'Require Settlement Before Session Close', 'Require settlement completion before closing session'),
            ],
        ),
        (
            2,
            'session_management',
            'Session Management',
            [
                ('allow_deferred_settlement', 'Allow Deferred Settlement', 'Allow settlement to be done later (next day)'),
                ('require_session_ownership_to_close', 'Require Session Ownership to Close', 'Only session starter can close the session'),
            ],
        ),
        (
            3,
            'billing_blocks',
            'Billing & Session Blocks',
            [
                ('block_billing_on_pending_settlement', 'Block Billing on Pending Settlement', 'Block billing if previous session has pending settlement'),
                ('block_session_start_on_pending_settlement', 'Block Session Start on Pending Settlement', 'Block new session start if previous session has pending settlement'),
            ],
        ),
        (
            4,
            'notifications',
            'Notifications',
            [
                ('show_pending_settlement_alert', 'Show Pending Settlement Alert', 'Show alert for pending settlements on POS open'),
                ('auto_remind_pending_settlement', 'Auto Remind Pending Settlement', 'Automatically remind about pending settlements'),
            ],
        ),
    ]

    for category_sequence, key, title, fields in categories:
        for index, (field_name, label, description) in enumerate(fields, start=1):
            Definition.objects.update_or_create(
                field_name=field_name,
                defaults={
                    'category_key': key,
                    'category_title': title,
                    'category_sequence': category_sequence,
                    'field_label': label,
                    'description': description,
                    'sequence': index,
                    'is_active': True,
                },
            )


def clear_settlement_definitions(apps, schema_editor):
    Definition = apps.get_model('business_rules', 'SettlementSettingDefinition')
    Definition.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('business_rules', '0004_alter_businessrule_options_businessrule_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementSettingDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_key', models.CharField(max_length=64)),
                ('category_title', models.CharField(max_length=128)),
                ('category_sequence', models.PositiveIntegerField(default=1)),
                ('field_name', models.CharField(max_length=128, unique=True)),
                ('field_label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settlement Setting Definition',
                'verbose_name_plural': 'Settlement Setting Definitions',
                'db_table': 'settlement_setting_definitions',
                'ordering': ['category_sequence', 'sequence'],
            },
        ),
        migrations.RunPython(seed_settlement_definitions, clear_settlement_definitions),
    ]
