# Generated by Django 5.2.9 on 2025-12-12 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_company_purchaseorder_company_and_more'),
        ('organization', '0003_company_logo'),
        ('products', '0010_item_itemvariant_variantattribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.itemvariant'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.itemvariant'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.itemvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('company', 'product')},
        ),
    ]
