# Generated by Django 5.0.1 on 2025-10-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='settlement_status',
            field=models.CharField(choices=[('pending', 'Settlement Pending'), ('completed', 'Settlement Completed')], default='pending', help_text='Settlement completion status for deferred settlement flow', max_length=20),
        ),
    ]
