# Generated by Django 5.0.1 on 2025-11-01 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_settlement_status'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='location',
            field=models.ForeignKey(help_text='Store location where sale was made', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='organization.location'),
        ),
        migrations.AddField(
            model_name='sale',
            name='terminal',
            field=models.ForeignKey(blank=True, help_text='Terminal/Till where sale was made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos_masters.terminal'),
        ),
        # Data migration to set default location for existing sales (if any)
        migrations.RunPython(
            migrations.RunPython.noop,  # No-op since we likely have no sales data
            reverse_code=migrations.RunPython.noop,
        ),
        # Make location non-nullable after setting defaults
        migrations.AlterField(
            model_name='sale',
            name='location',
            field=models.ForeignKey(help_text='Store location where sale was made', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='organization.location'),
        ),
    ]
