# Generated by Django 5.0.1 on 2025-11-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20251101_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='subtotal',
            new_name='line_total',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='total',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
