# Generated by Django 5.0.1 on 2025-11-01 08:24

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('organization', '0003_company_logo'),
        ('pos_masters', '0004_printertemplate_terminal_terminaldepartmentmapping_and_more'),
        ('products', '0007_brand_department_division'),
        ('sales', '0004_rename_sale_item_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayClose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_date', models.DateField(db_index=True, help_text='Business date (sale date) that is being closed')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reverted', 'Reverted')], default='pending', max_length=20)),
                ('checklist_items', models.JSONField(default=dict, help_text='JSON object tracking completion of checklist items')),
                ('total_transactions', models.IntegerField(default=0, help_text='Total number of transactions for the day')),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total sales amount for the day', max_digits=18)),
                ('total_sessions', models.IntegerField(default=0, help_text='Number of sessions closed')),
                ('total_items_sold', models.IntegerField(default=0, help_text='Total items sold')),
                ('next_sale_number', models.CharField(default='SALE-YYYYMMDD-0001', help_text='Next sale number sequence for next business date', max_length=50)),
                ('next_session_number', models.CharField(default='SES-YYYYMMDD-0001', help_text='Next session number sequence for next business date', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the day close')),
                ('errors', models.JSONField(default=list, help_text='Any errors encountered during day close')),
                ('warnings', models.JSONField(default=list, help_text='Warnings during day close')),
            ],
            options={
                'db_table': 'day_closes',
                'ordering': ['-business_date', '-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='DayOpen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_date', models.DateField(db_index=True, help_text='Business date (sale date) being opened')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('next_sale_number', models.CharField(default='SALE-YYYYMMDD-0001', help_text='Next sale number sequence for this business date', max_length=50)),
                ('next_session_number', models.CharField(default='SES-YYYYMMDD-0001', help_text='Next session number sequence for this business date', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this day open still active?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the day open')),
            ],
            options={
                'db_table': 'day_opens',
                'ordering': ['-business_date', '-opened_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_nu_ee8c51_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_status_a83c6f_idx',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='delivery_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='delivery_phone',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='salesman',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='possession',
            name='close_mode',
            field=models.CharField(blank=True, choices=[('temporary', 'Temporary'), ('permanent', 'Permanent')], help_text='Mode of closing: temporary (can reopen) or permanent (final close)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('cheque', 'Cheque'), ('credit', 'Credit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_cashier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='sale',
            name='pos_session',
            field=models.ForeignKey(blank=True, help_text='POS session during which this sale was made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.possession'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partial_refund', 'Partially Refunded')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'sale_date'], name='sales_status_cd1c67_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['location', 'sale_date'], name='sales_locatio_d5199d_idx'),
        ),
        migrations.AddField(
            model_name='dayclose',
            name='initiated_by',
            field=models.ForeignKey(help_text='User who initiated the day close', on_delete=django.db.models.deletion.PROTECT, related_name='day_closes_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayclose',
            name='location',
            field=models.ForeignKey(help_text='Store location for this day close', limit_choices_to={'location_type': 'store'}, on_delete=django.db.models.deletion.PROTECT, related_name='day_closes', to='organization.location'),
        ),
        migrations.AddField(
            model_name='dayclose',
            name='reverted_by',
            field=models.ForeignKey(blank=True, help_text='User who reverted the day close', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_closes_reverted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayopen',
            name='closed_by',
            field=models.ForeignKey(blank=True, help_text='User who closed the day open', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_opens_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayopen',
            name='location',
            field=models.ForeignKey(help_text='Store location for this day open', limit_choices_to={'location_type': 'store'}, on_delete=django.db.models.deletion.PROTECT, related_name='day_opens', to='organization.location'),
        ),
        migrations.AddField(
            model_name='dayopen',
            name='opened_by',
            field=models.ForeignKey(help_text='User who opened the business day', on_delete=django.db.models.deletion.PROTECT, related_name='day_opens_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dayclose',
            index=models.Index(fields=['location', 'business_date'], name='day_closes_locatio_e0f62b_idx'),
        ),
        migrations.AddIndex(
            model_name='dayclose',
            index=models.Index(fields=['status', 'business_date'], name='day_closes_status_020b79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dayclose',
            unique_together={('location', 'business_date')},
        ),
        migrations.AddIndex(
            model_name='dayopen',
            index=models.Index(fields=['location', 'business_date'], name='day_opens_locatio_369c23_idx'),
        ),
        migrations.AddIndex(
            model_name='dayopen',
            index=models.Index(fields=['is_active'], name='day_opens_is_acti_b8a015_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dayopen',
            unique_together={('location', 'business_date')},
        ),
    ]
