# Generated by Django 5.0.1 on 2025-11-02 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_company_logo'),
        ('pos_masters', '0004_printertemplate_terminal_terminaldepartmentmapping_and_more'),
        ('sales', '0005_dayclose_dayopen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location where this session is opened', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='organization.location'),
        ),
        migrations.AddField(
            model_name='possession',
            name='terminal',
            field=models.ForeignKey(blank=True, help_text='Terminal/Till where this session is opened', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='pos_masters.terminal'),
        ),
    ]
