# Generated by Django 5.0.1 on 2025-11-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_itemmaster_item_category_and_more'),
        ('sales', '0007_possession_settlement_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.itemmaster'),
        ),
    ]
