# Generated by Django 5.2.9 on 2025-12-12 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_company_logo'),
        ('products', '0011_delete_product_and_more'),
        ('sales', '0008_alter_saleitem_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dayclose',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dayopen',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dayclose',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_closes', to='organization.company'),
        ),
        migrations.AddField(
            model_name='dayopen',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_opens', to='organization.company'),
        ),
        migrations.AddField(
            model_name='possession',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_sessions', to='organization.company'),
        ),
        migrations.AddField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='organization.company'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.itemvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='dayclose',
            unique_together={('company', 'location', 'business_date')},
        ),
        migrations.AlterUniqueTogether(
            name='dayopen',
            unique_together={('company', 'location', 'business_date')},
        ),
        migrations.AlterUniqueTogether(
            name='possession',
            unique_together={('company', 'session_number')},
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('company', 'sale_number')},
        ),
    ]
