# Generated by Django 5.0.1 on 2025-10-25 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(choices=[('blue', 'Blue Theme'), ('black', 'Black Theme')], default='blue', help_text='Selected theme for the system', max_length=20)),
                ('primary_color', models.CharField(default='#1565C0', help_text='Primary color hex code', max_length=7)),
                ('secondary_color', models.CharField(default='#FF5722', help_text='Secondary color hex code', max_length=7)),
                ('background_color', models.CharField(default='#f5f5f5', help_text='Background color hex code', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this theme is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this theme setting', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Theme Setting',
                'verbose_name_plural': 'Theme Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
