# Generated by Django 5.2.7 on 2025-11-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themesetting',
            options={'ordering': ['theme_name'], 'verbose_name': 'Theme Setting', 'verbose_name_plural': 'Theme Settings'},
        ),
        migrations.AddField(
            model_name='themesetting',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is a default system theme'),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='name',
            field=models.CharField(default='', help_text='Display name for the theme', max_length=50),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='text_color',
            field=models.CharField(default='#000000', help_text='Text color hex code', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Background color hex code', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether this theme is currently active'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='primary_color',
            field=models.CharField(default='#1976D2', help_text='Primary color hex code (e.g., #FF0000)', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='secondary_color',
            field=models.CharField(default='#2196F3', help_text='Secondary color hex code (e.g., #FF5722)', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='theme_name',
            field=models.CharField(choices=[('red', 'Red Theme'), ('green', 'Green Theme'), ('blue', 'Blue Theme'), ('black', 'Black Theme')], default='blue', help_text='Theme identifier for the system', max_length=20),
        ),
    ]
