# Generated by Django 5.0.1 on 2025-11-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_management', '0002_alter_themesetting_options_themesetting_is_default_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themesetting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Theme Setting', 'verbose_name_plural': 'Theme Settings'},
        ),
        migrations.RemoveField(
            model_name='themesetting',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='themesetting',
            name='name',
        ),
        migrations.RemoveField(
            model_name='themesetting',
            name='text_color',
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='background_color',
            field=models.CharField(default='#f5f5f5', help_text='Background color hex code', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this theme is currently active'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='primary_color',
            field=models.CharField(default='#1565C0', help_text='Primary color hex code', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='secondary_color',
            field=models.CharField(default='#FF5722', help_text='Secondary color hex code', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='theme_name',
            field=models.CharField(choices=[('blue', 'Blue Theme'), ('black', 'Black Theme')], default='blue', help_text='Selected theme for the system', max_length=20),
        ),
    ]
