# Generated by Django 5.0.1 on 2025-10-25 03:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('SYSTEM', 'System Codes'), ('TRANSACTION', 'Transaction Codes'), ('CUSTOMER', 'Customer Codes'), ('PRODUCT', 'Product Codes'), ('PAYMENT', 'Payment Codes'), ('TAX', 'Tax Codes'), ('DISCOUNT', 'Discount Codes'), ('LOYALTY', 'Loyalty Codes'), ('REPORT', 'Report Codes'), ('OTHER', 'Other Codes')], help_text='Category of the code setting', max_length=50)),
                ('code_type', models.CharField(help_text='Type of code (e.g., Invoice Prefix, Receipt Number)', max_length=100)),
                ('code_prefix', models.CharField(blank=True, help_text='Prefix for the code', max_length=10, null=True)),
                ('code_suffix', models.CharField(blank=True, help_text='Suffix for the code', max_length=10, null=True)),
                ('starting_number', models.IntegerField(default=1, help_text='Starting number for auto-generation')),
                ('current_number', models.IntegerField(default=0, help_text='Current number in sequence')),
                ('number_format', models.CharField(default='000000', help_text='Number format (e.g., 000000 for 6-digit numbers)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the code setting', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_generate', models.BooleanField(default=True, help_text='Whether to auto-generate codes')),
                ('reset_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('NEVER', 'Never')], default='NEVER', help_text='How often to reset the counter', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_settings_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code Setting',
                'verbose_name_plural': 'Code Settings',
                'db_table': 'code_settings',
                'ordering': ['category', 'code_type'],
                'unique_together': {('category', 'code_type')},
            },
        ),
        migrations.CreateModel(
            name='CodeSettingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('code_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='code_settings.codesetting')),
            ],
            options={
                'verbose_name': 'Code Setting History',
                'verbose_name_plural': 'Code Setting Histories',
                'db_table': 'code_setting_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSettingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=100, unique=True)),
                ('rule_type', models.CharField(choices=[('VALIDATION', 'Validation Rule'), ('GENERATION', 'Generation Rule'), ('FORMAT', 'Format Rule'), ('RESET', 'Reset Rule')], max_length=50)),
                ('rule_expression', models.TextField(help_text='Rule expression or logic')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code Setting Rule',
                'verbose_name_plural': 'Code Setting Rules',
                'db_table': 'code_setting_rules',
                'ordering': ['rule_name'],
            },
        ),
        migrations.CreateModel(
            name='CodeSettingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('code_type', models.CharField(max_length=100)),
                ('code_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('code_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('starting_number', models.IntegerField(default=1)),
                ('number_format', models.CharField(default='000000', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code Setting Template',
                'verbose_name_plural': 'Code Setting Templates',
                'db_table': 'code_setting_templates',
                'ordering': ['template_name'],
            },
        ),
    ]
