# Generated by Django 5.0.1 on 2025-10-25 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Program name (e.g., Point of Sale)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Program code (e.g., POS)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Program description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this program is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos_programs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pos_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS Program',
                'verbose_name_plural': 'POS Programs',
                'db_table': 'pos_programs',
                'ordering': ['name'],
            },
        ),
    ]
