# Generated by Django 5.0.1 on 2025-10-25 01:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Payment method name', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for payment method', max_length=20, unique=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('wallet', 'Digital Wallet'), ('cheque', 'Cheque'), ('credit', 'Credit'), ('other', 'Other')], help_text='Type of payment', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of payment method', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is active')),
                ('requires_authorization', models.BooleanField(default=False, help_text='Requires manager authorization')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum transaction amount', max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=999999.99, help_text='Maximum transaction amount', max_digits=10)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display in POS')),
                ('icon_name', models.CharField(blank=True, help_text='Icon name for UI', max_length=50, null=True)),
                ('color_code', models.CharField(default='#2196F3', help_text='Color code for UI (hex)', max_length=7)),
                ('allow_refund', models.BooleanField(default=True, help_text='Allow refunds through this method')),
                ('allow_partial_refund', models.BooleanField(default=True, help_text='Allow partial refunds')),
                ('requires_receipt', models.BooleanField(default=False, help_text='Requires receipt printing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymodes_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymodes_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pay Mode',
                'verbose_name_plural': 'Pay Modes',
                'db_table': 'pay_modes',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayModeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text='Field that was changed', max_length=50)),
                ('old_value', models.TextField(help_text='Previous value')),
                ('new_value', models.TextField(help_text='New value')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for change', null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paymode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='pay_modes.paymode')),
            ],
            options={
                'verbose_name': 'Pay Mode History',
                'verbose_name_plural': 'Pay Mode History',
                'db_table': 'pay_mode_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PayModeSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('require_payment_confirmation', models.BooleanField(default=False, help_text='Require confirmation for all payments')),
                ('allow_multiple_payments', models.BooleanField(default=True, help_text='Allow multiple payment methods per transaction')),
                ('enable_cash_drawer', models.BooleanField(default=True, help_text='Enable cash drawer functionality')),
                ('auto_open_cash_drawer', models.BooleanField(default=False, help_text='Auto-open cash drawer on cash payment')),
                ('enable_card_payments', models.BooleanField(default=True, help_text='Enable card payment processing')),
                ('require_card_pin', models.BooleanField(default=False, help_text='Require PIN for card transactions')),
                ('enable_upi_payments', models.BooleanField(default=True, help_text='Enable UPI payment processing')),
                ('enable_qr_code', models.BooleanField(default=True, help_text='Enable QR code generation')),
                ('allow_refunds', models.BooleanField(default=True, help_text='Allow refunds in POS')),
                ('require_refund_authorization', models.BooleanField(default=True, help_text='Require authorization for refunds')),
                ('max_refund_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Maximum refund percentage allowed', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_cash_paymode', models.ForeignKey(blank=True, help_text='Default cash payment method', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_cash_settings', to='pay_modes.paymode')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymode_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pay Mode Settings',
                'verbose_name_plural': 'Pay Mode Settings',
                'db_table': 'pay_mode_settings',
            },
        ),
    ]
