# Generated by Django 5.0.1 on 2025-11-07 16:07

import uuid
from django.db import migrations, models


def seed_paymode_definitions(apps, schema_editor):
    Definition = apps.get_model('pay_modes', 'PayModeSettingDefinition')

    categories = [
        (
            1,
            'general',
            'General Settings',
            [
                ('require_payment_confirmation', 'Require Payment Confirmation', 'Ask for confirmation before finalizing payments'),
                ('allow_multiple_payments', 'Allow Multiple Payments', 'Permit combining payment methods in a single bill'),
            ],
        ),
        (
            2,
            'cash_handling',
            'Cash Handling',
            [
                ('enable_cash_drawer', 'Enable Cash Drawer', 'Allow integration with cash drawer hardware'),
                ('auto_open_cash_drawer', 'Auto-open Cash Drawer', 'Automatically open cash drawer after cash payments'),
            ],
        ),
        (
            3,
            'card_settings',
            'Card Settings',
            [
                ('enable_card_payments', 'Enable Card Payments', 'Allow card transactions at POS'),
                ('require_card_pin', 'Require Card PIN', 'Mandatory PIN entry for card payments'),
            ],
        ),
        (
            4,
            'digital_payments',
            'Digital Payments',
            [
                ('enable_upi_payments', 'Enable UPI Payments', 'Allow Unified Payments Interface (UPI) transactions'),
                ('enable_qr_code', 'Enable QR Code', 'Display QR codes for digital payment collection'),
            ],
        ),
        (
            5,
            'refund_settings',
            'Refund Settings',
            [
                ('allow_refunds', 'Allow Refunds', 'Permit refund processing at POS'),
                ('require_refund_authorization', 'Require Refund Authorization', 'Mandate supervisor approval before processing refunds'),
                ('max_refund_percentage', 'Maximum Refund Percentage', 'Upper limit on refundable amount compared to original bill'),
            ],
        ),
    ]

    for category_sequence, key, title, fields in categories:
        for index, (field_name, label, description) in enumerate(fields, start=1):
            Definition.objects.update_or_create(
                field_name=field_name,
                defaults={
                    'category_key': key,
                    'category_title': title,
                    'category_sequence': category_sequence,
                    'field_label': label,
                    'description': description,
                    'sequence': index,
                    'is_active': True,
                },
            )


def clear_paymode_definitions(apps, schema_editor):
    Definition = apps.get_model('pay_modes', 'PayModeSettingDefinition')
    Definition.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pay_modes', '0002_create_default_payment_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayModeSettingDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_key', models.CharField(max_length=64)),
                ('category_title', models.CharField(max_length=128)),
                ('category_sequence', models.PositiveIntegerField(default=1)),
                ('field_name', models.CharField(max_length=128, unique=True)),
                ('field_label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pay Mode Setting Definition',
                'verbose_name_plural': 'Pay Mode Setting Definitions',
                'db_table': 'paymode_setting_definitions',
                'ordering': ['category_sequence', 'sequence'],
            },
        ),
        migrations.RunPython(seed_paymode_definitions, clear_paymode_definitions),
    ]
