# Generated by Django 5.2.9 on 2025-12-12 14:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_company_logo'),
        ('procurement', '0001_initial'),
        ('products', '0009_remove_itemmaster_item_category_and_more'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('pr_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PARTIALLY_ORDERED', 'Partially Ordered'), ('FULLY_ORDERED', 'Fully Ordered'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('approval_required', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('converted_to_po', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_prs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='organization.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prs', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_prs', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_prs', to=settings.AUTH_USER_MODEL)),
                ('requesting_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='organization.location')),
                ('supplier_hint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_hints', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'purchase_requisition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_qty', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('already_ordered_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('line_remarks', models.TextField(blank=True)),
                ('line_status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_ORDERED', 'Partially Ordered'), ('FULLY_ORDERED', 'Fully Ordered'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('line_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_pr_lines', to='products.itemmaster')),
                ('purchase_requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaserequisition')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uom_pr_lines', to='products.uom')),
            ],
            options={
                'db_table': 'purchase_requisition_line',
                'ordering': ['purchase_requisition', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionPOLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_order', models.UUIDField(help_text='Reference to Purchase Order ID')),
                ('po_line', models.UUIDField(help_text='Reference to Purchase Order Line ID')),
                ('ordered_qty_from_pr', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pr_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_links', to='procurement.purchaserequisitionline')),
            ],
            options={
                'db_table': 'purchase_requisition_po_link',
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['company', 'pr_status'], name='purchase_re_company_be2251_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['requesting_location', 'pr_status'], name='purchase_re_request_77a1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['created_at'], name='purchase_re_created_c47a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['pr_number'], name='purchase_re_pr_numb_65b924_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisitionline',
            index=models.Index(fields=['purchase_requisition', 'line_status'], name='purchase_re_purchas_d86883_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisitionline',
            index=models.Index(fields=['item', 'line_status'], name='purchase_re_item_id_3b2d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisitionpolink',
            index=models.Index(fields=['pr_line'], name='purchase_re_pr_line_5c4475_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisitionpolink',
            index=models.Index(fields=['purchase_order'], name='purchase_re_purchas_6697c1_idx'),
        ),
    ]
