# Generated by Django 5.2.9 on 2025-12-12 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_purchaserequisition_purchaserequisitionline_and_more'),
        ('products', '0010_item_itemvariant_variantattribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednoteitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.itemvariant'),
        ),
        migrations.AlterField(
            model_name='purchaseenquiryitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.itemvariant'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.itemvariant'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='products.itemvariant'),
        ),
        migrations.AlterField(
            model_name='purchasequotationitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.itemvariant'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_items', to='products.itemvariant'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_pr_lines', to='products.itemvariant'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.itemvariant'),
        ),
    ]
