# Generated by Django 5.0.1 on 2025-10-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_update_role_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('posmanager', 'POS Manager'), ('posuser', 'POS User'), ('backofficemanager', 'Back Office Manager'), ('backofficeuser', 'Back Office User'), ('manager', 'Manager'), ('cashier', 'Cashier')], default='cashier', max_length=30),
        ),
    ]
