# Generated by Django 5.0.1 on 2025-10-31 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_update_role_field_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('posmanager', 'POS Manager'), ('posuser', 'POS User'), ('backofficemanager', 'Back Office Manager'), ('backofficeuser', 'Back Office User')], default='posuser', max_length=30),
        ),
        migrations.CreateModel(
            name='MenuItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('menu_type', models.CharField(choices=[('MASTER', 'Master'), ('SECURITY', 'Security'), ('TRANSACTION', 'Transaction'), ('SYSTEM', 'System'), ('DASHBOARD', 'Dashboard')], max_length=20)),
                ('transaction_subtype', models.CharField(blank=True, choices=[('POS', 'POS'), ('BACKOFFICE', 'BackOffice'), (None, 'N/A')], help_text='Only applicable for TRANSACTION type', max_length=20, null=True)),
                ('category', models.CharField(help_text="Menu category (e.g., 'Master Data Management')", max_length=100)),
                ('path', models.CharField(help_text='Frontend route path', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu Item Type',
                'verbose_name_plural': 'Menu Item Types',
                'db_table': 'menu_item_types',
                'ordering': ['category', 'order', 'display_name'],
                'indexes': [models.Index(fields=['menu_type'], name='menu_item_t_menu_ty_4b2752_idx'), models.Index(fields=['transaction_subtype'], name='menu_item_t_transac_5ff680_idx'), models.Index(fields=['category'], name='menu_item_t_categor_d62549_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(help_text="Role key for quick lookup (e.g., 'posmanager', 'posuser')", max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to='auth.group')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='users.menuitemtype', to_field='menu_item_id')),
            ],
            options={
                'verbose_name': 'Group Permission',
                'verbose_name_plural': 'Group Permissions',
                'db_table': 'group_permissions',
                'indexes': [models.Index(fields=['role_key', 'menu_item'], name='group_permi_role_ke_4fca0d_idx'), models.Index(fields=['group', 'menu_item'], name='group_permi_group_i_41d3ba_idx')],
                'unique_together': {('group', 'menu_item')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False, help_text='Can view/access the page')),
                ('can_create', models.BooleanField(default=False, help_text='Can create new records')),
                ('can_edit', models.BooleanField(default=False, help_text='Can edit existing records')),
                ('can_delete', models.BooleanField(default=False, help_text='Can delete records')),
                ('override', models.BooleanField(default=False, help_text='Override group/role permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permissions', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='users.menuitemtype', to_field='menu_item_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'db_table': 'user_permissions',
                'indexes': [models.Index(fields=['user', 'menu_item'], name='user_permis_user_id_8e9f7d_idx'), models.Index(fields=['menu_item', 'can_view'], name='user_permis_menu_it_34d78c_idx')],
                'unique_together': {('user', 'menu_item')},
            },
        ),
    ]
