# Generated by Django 5.0.1 on 2025-10-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_permission_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermission',
            name='can_access',
            field=models.BooleanField(default=False, help_text='Can access/see the menu item (controls visibility)'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='can_access',
            field=models.BooleanField(default=False, help_text='Can access/see the menu item (controls visibility)'),
        ),
    ]
