# Generated by Django 5.0.1 on 2025-10-31 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_company_logo'),
        ('users', '0005_grouppermission_can_access_userpermission_can_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pos_location',
            field=models.ForeignKey(blank=True, help_text='POS location assignment (only for POS users, one location per user)', limit_choices_to={'is_active': True, 'location_type': 'store'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_users', to='organization.location'),
        ),
    ]
