# Generated by Django 5.0.1 on 2025-11-06 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_pos_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('function_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('BASIC', 'Basic Operations'), ('DISCOUNT', 'Discount Operations'), ('PAYMENT', 'Payment Operations'), ('TRANSACTION', 'Transaction Management'), ('ADMIN', 'Administrative')], max_length=20)),
                ('keyboard_shortcut', models.CharField(max_length=20)),
                ('is_critical', models.BooleanField(default=False, help_text='Requires special authorization')),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'POS Function',
                'verbose_name_plural': 'POS Functions',
                'db_table': 'pos_functions',
                'ordering': ['category', 'order'],
                'indexes': [models.Index(fields=['function_code'], name='pos_functio_functio_d31cc4_idx'), models.Index(fields=['category', 'is_active'], name='pos_functio_categor_b772f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePOSFunctionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('posmanager', 'POS Manager'), ('posuser', 'POS User'), ('backofficemanager', 'Back Office Manager'), ('backofficeuser', 'Back Office User')], max_length=30)),
                ('is_allowed', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False, help_text='For critical functions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos_function_mappings', to=settings.AUTH_USER_MODEL)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='users.posfunction')),
            ],
            options={
                'verbose_name': 'Role POS Function Mapping',
                'verbose_name_plural': 'Role POS Function Mappings',
                'db_table': 'role_pos_function_mappings',
                'indexes': [models.Index(fields=['role', 'is_allowed'], name='role_pos_fu_role_a51a16_idx'), models.Index(fields=['function', 'role'], name='role_pos_fu_functio_a1bf1e_idx')],
                'unique_together': {('role', 'function')},
            },
        ),
    ]
