# Generated by Django 5.2.7 on 2025-11-11 01:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_company_logo'),
        ('users', '0007_posfunction_roleposfunctionmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocationMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('back_office', 'Back Office'), ('pos', 'POS'), ('both', 'Both')], default='back_office', help_text='Type of access user has at this location', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Mark as default location for this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_location_mappings', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='organization.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Location Mapping',
                'verbose_name_plural': 'User Location Mappings',
                'db_table': 'user_location_mappings',
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_locati_user_id_02f44f_idx'), models.Index(fields=['location', 'is_active'], name='user_locati_locatio_729dec_idx'), models.Index(fields=['access_type', 'is_active'], name='user_locati_access__36f40c_idx')],
                'unique_together': {('user', 'location', 'access_type')},
            },
        ),
    ]
