# Generated by Django 5.2.7 on 2025-11-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userlocationmapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemtype',
            options={'ordering': ['category', 'order', 'display_name'], 'verbose_name': 'Menu Controller', 'verbose_name_plural': 'Menu Controller'},
        ),
        migrations.AddField(
            model_name='menuitemtype',
            name='subcategory',
            field=models.CharField(blank=True, help_text="Menu subcategory for grouping (e.g., 'Admin Tools', 'Business Rules')", max_length=100, null=True),
        ),
    ]
