# Generated by Django 5.0.1 on 2025-10-02 15:21

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_code', models.CharField(help_text='Unique supplier code (auto-generated)', max_length=20, unique=True)),
                ('company_name', models.CharField(help_text='Supplier company name', max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('trade_name', models.CharField(blank=True, help_text='Trade name or DBA (Doing Business As)', max_length=200, null=True)),
                ('supplier_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('dropshipper', 'Drop Shipper'), ('service_provider', 'Service Provider')], default='distributor', help_text='Type of supplier', max_length=20)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person name', max_length=100, null=True)),
                ('contact_title', models.CharField(blank=True, help_text="Contact person's title/position", max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Primary email address', max_length=254, null=True)),
                ('phone', models.CharField(help_text='Primary phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('mobile', models.CharField(blank=True, help_text='Mobile phone number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('website', models.URLField(blank=True, help_text='Company website URL', null=True)),
                ('address_line_1', models.CharField(blank=True, help_text='Street address line 1', max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, help_text='Street address line 2 (optional)', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State/Province', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20, null=True)),
                ('country', models.CharField(default='United States', help_text='Country', max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID/EIN number', max_length=50, null=True)),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15 Days'), ('net_30', 'Net 30 Days'), ('net_45', 'Net 45 Days'), ('net_60', 'Net 60 Days'), ('cod', 'Cash on Delivery'), ('prepaid', 'Prepaid'), ('credit_card', 'Credit Card'), ('custom', 'Custom Terms')], default='net_30', help_text='Default payment terms', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Credit limit with this supplier', max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Default discount percentage from supplier', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this supplier is active')),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred supplier status')),
                ('is_verified', models.BooleanField(default=False, help_text='Supplier verification status')),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='Average lead time in days')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order amount', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the supplier', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_order_date', models.DateTimeField(blank=True, help_text='Date of last purchase order', null=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers',
                'ordering': ['company_name'],
                'indexes': [models.Index(fields=['supplier_code'], name='suppliers_supplie_e2938c_idx'), models.Index(fields=['company_name'], name='suppliers_company_2938da_idx'), models.Index(fields=['email'], name='suppliers_email_633111_idx'), models.Index(fields=['phone'], name='suppliers_phone_a7f316_idx'), models.Index(fields=['supplier_type'], name='suppliers_supplie_8818cc_idx'), models.Index(fields=['is_active'], name='suppliers_is_acti_a163b0_idx')],
            },
        ),
    ]
